# Intro to Economics

## Reading 1

### What is Economics?

What do you think of when you hear the word economics? Many people think of "the economy" and more specifically how the stock market is preforming and how expensive things are, but economics is so much more than this. Some definitions of economics are given below. 

**Definitions in dictionaries**

- Merriam-Webster Dictionary: "A social science concerned chiefly with description and analysis of the production, distribution, and consumption of goods and services"
- Oxford Learners Dictionary: "The study of how a society organizes its money, trade, and industry"
- Cambridge Dictionary: "The way in which trade, industry, or money is organized, or the study of this"

**Definition from the American Economic Association**

>It’s the study of scarcity, the study of how people use resources and respond to incentives, or the study of decision-making

A key difference in these definitions is the focus on decision making under scarcity and responses to incentives. **Scarcity** comes when we are unable to meet all out wants. Scarcity can come in the form of not having enough money to buy an item that you want, or it could be that you do not have enough time in the day to do all the activities you want. Because we face scarcity, we must decide how to allocate resources, energy, time, etc. People choose how to allocate scare items through incentives. **Incentives** are rewards that encourage a behavior or punishments that discourage a behavior. For example, if you have 2 hours of free time to either work on homework or hang out with your friends, you must choose which to do. You cannot spend 2 hours with your friends and 2 hours doing homework because you only have 2 hours of free time total. Right now you may choose to hang out with your friends because you enjoy spending time with your friends (large benefit), and there are not many assignments due in class yet (low costs). However, if you have a test tomorrow, then the cost of spending those two hours with your friends is much higher (cost is the loss of points on your test). In this case you may choose to allocate your scarce time differently because your incentives have changed. 

### Two Branches of Economics

Economics can be broken down into two main branches of study. 

1. **Microeconomics** - the study of the choices that individuals and businesses make, the way these choices interact in markets, and the influence of governments.
2. **Macroeconomics** - the study of the performance of the national economy and the global economy. 

Some questions microeconomists study are:

- How does legalization of sports betting affect the rate of domestic disputes?
- How do union contracts affect the retention of teachers and educational attainment of students? 
- How does accuracy of past hurricane forecasts affect rates of emergency supply purchases?

Some questions macroeconomists study are:

- How does access to banks and credit affect expenditure of developing nations? 
- How do trade agreements affect the division of the labor force along different demographic lines?
- How did the historical development of infrastructure affect the employment and economic growth rates of different regions in a country?

### The Economic Way of Thinking 

**1. A choice is a trade-off.**
A **trade-off** is when you must give up one thing for another. This was discussed already when we talked about scarcity and allocating your time between doing homework and hanging out with your friends. 

 

**2. People make rational choices by comparing costs and benefits.**
Economists believe that people purchase and do things because they believe that the benefits outweigh the costs. For example, if you like strawberry ice-cream and are allergic to peanuts, then if you go to an ice-cream store we can assume that you will not choose an ice-cream with peanuts but will get one with strawberries. Specifically, you get more benefit from a strawberry ice-cream than the cost of purchasing, but the cost of peanut ice-cream is very high and the benefit is extremely low. Since the benefits are higher than the costs for strawberry and not peanut then a rational consumer will only buy strawberry ice-cream.

 

**3. Benefit is what you gain from something.**
**Preferences** are how much you like or dislike something. If you prefer Coke to Pepsi, then the benefit you get from a can of Coke is greater than the benefit your get from a can of Pepsi. Preferences are personal, and just because you have a preference for Coke does not mean that someone cannot have a preference for Pepsi.

 

**4. Cost is what you must give up for something.**
Costs can be the amount of money you spend on something, but it does not have to be money. Suppose, when choosing your course schedule, you need to pick between two electives: environmental economics and international economics. If you choose to take environmental economics, then you must give up taking international economics. International economics is the cost of taking environmental economics. This type of cost is called an **opportunity cost**, the highest valued option that must be given up.

 

**5. Most choices are "how-much" choices made on the margin.**
Choices made on the **margin** are made by comparing a little more of something with its cost. If you are eating a pizza, you will choose how many slices to eat. Each slide will satiate a bit of your hunger. As you eat more and more slices, your hunger decreases along with the benefit of eating an additional slice. Once you are no longer hungry, you will stop eating pizza because the benefit of another slice is less than the cost of an upset stomach from eating too much.

 

**6. Choices respond to incentives.**
When discussing the choice to work on homework or hang our with friends, we mentioned that if you had a test, then the incentives were different, than the first week of the quarter. Because the incentives are different, your choice between hanging out with friends and doing homework will be different.

 

### Economics as a Social Science and Policy Tool

Economic research is done as a way to inform and critique policy. We make extensive use of facts and data to show how things in the world are or how a policy is working, and from this information we can make suggestions for new policy. Statements that declare facts and can be tested in economics research are **positive statements** while statements about how the world should be are **normative statements**. While it is tempting to start research or arguments with normative statements because you are passionate about a specific policy or topic, you cannot support your research or position without positive statements. 

### Why Study Economics? 

Economics is more than just understanding money and the "economy". Economics is a toolset, a way of thinking, a way of approaching the world that is just a little bit different. Economics courses do so much more than teach you how to set a price for a product or how to interpret interest rates (although these are important). Economics teaches you to analyze all possibilities. It teaches you to think about the direct consequences of a decision as well as the indirect consequences. Economics teaches you to look beyond simple correlations in data, and to find the causes of relationship. Economics teaches you invaluable logic, reasoning, and critical thinking skill that can translate to all future careers as well as keep you marketable as an employee in a world surrounded by artificial intelligence. 

Students with economics majors can go into a wide variety of fields including government work, entrepreneurship, law, finance, consulting, and business analytics. Economics majors also have some of the highest salaries and career stability outside of engineering and medical degrees.

As artificial intelligence becomes more prevalent, job security is becoming uncertain in many sectors. Some economics jobs will also be affected by this. However, in this class we will focus on the tools required to make you all better prepared for the AI job market. You will focus on understanding the reasoning and logic behind arguments. You will learn how to critique and review AI output. You will also learn about writing AI prompts to give better results. The combination of computer skills and judgement is what make economics majors still highly desirable even as the job market changes. 

## Exercises 1

## Reading 2

### Graphs and Models in Economics

## Exercises 2

