# Taxes

One of the government regulations that we see nearly every day of our lives is taxes. We pay sales tax when we by things at the store. We pay per gallon taxes on gasoline for our cars. You pay income tax when you get a paycheck. If you ever own a home, you will pay property taxes. A **tax **is an amount paid to the government when certain goods and services are purchased. Taxes can come in two forms. If you pay a percentage on the total amount of the purchase (like sales tax) we call it a **percent tax**. A tax of an exact amount for every item you purchase (like for gasoline) is a **flat tax**, or per-unit tax.

When the government implements a tax, they can either put the tax on the consumer or on the producer. However, what we care about in economics is not the wording of the policy, but who ends up paying for the tax at the end of the day. Do the companies pass the tax of to the consumers or do they pay for it themselves? The split of tax between the producers and the consumers is what we call the **tax incidence**, or tax burden. The reason we do not care about who the tax is initially places on is because the tax incidence is the same for both.

### A Tax on Consumers

The city of Seattle implemented a sugar tax in 2018 that charges \$0.0175 on every ounce of soda and other sugary beverages purchased. This amounts to a \$2.52 tax on a twelve pack of soda cans. We will start by analyzing the soda market before the tax.


Suppose that the market for soda in Seattle without a tax followed the graph below, **and was an efficient market**. Quantity here is thousands of 12-packs of soda sold per month and price is in dollars.

The current market equilibrium is a price of \$5 per 12-pack and 20,000 12-packs of soda sold per month.

Placing the tax on the consumer means that when we purchase the good, we must give the tax to the government. In economics we think about this as either increasing the costs or reducing the benefits received by consumers. We show this by decreasing the demand curve by the amount of the tax.

The point where the supply and demand with tax intersects gives us the new market quantity. We can see that this quantity is lower than the quantity without the tax.

### Taxes as a price wedge

Because consumers have to pay a tax when purchasing the good, the price they see, is not the final price they will pay. Consumers will pay the listed price for the good or service and then will pay the tax to the government on top of this. This means that the price for the consumer is different than the amount of money received by the producer.

Even though the tax must be paid by consumers, the decrease in demand also affects the producers. Originally consumers paid \$5 and the producer received \$5. Now the consumer pay \$6.26 for the same good, but the producer only gets \$3.74. The groups who's price was changed the most is the group that bears the tax burden. Here the producers lose \$1.26 per 12 pack and the consumers pay an extra \$1.26 per 12 pack, so the split is the same.

### Taxes and Market Efficiency
Because the tax moves the market away from equilibrium, we will see deadweight loss occur, and a decrease in economic surplus. When there are taxes, we also get government revenue. For every item that is purchased, the government is paid the tax amount. The graph below shows how the areas are affected by different tax amount.


### A Tax on Producers

A tax on producers means that after they receive payment from the consumer, they must give some of that payment to the government. We can think of the tax as increasing the cost to producers therefore reducing supply. We know that a reduction in supply reduced the equilibrium market quantity and raises the equilibrium price. Just like before the tax creates a difference in the final prices for the consumer and producers. The consumers pay the new higher equilibrium price, but the producer does not keep this amount. The producer must give the tax amount to the government and ultimately takes home a lower price. The graph below shows the same market for soda in Seattle with the tax placed on the producers. Notice that the equilibrium prices and quantities are same as when the tax was on the consumers.



Since the resulting prices and quantities are the same, the tax burden is the same, as well as the effect on economic surplus and deadweight loss. By changing the tax below you can see how the affect on surplus is the same as when the tax was on consumers.


## Elasticity and Who Pays the Tax

In the example above, the elasticity of demand was always equal to the elasticity of supply. This resulted in the effect of the tax being the same of producers and consumers. However, more often it is the case that there are different elasticities. Who ever has the least elastic curve, will end up paying for more of the tax. This is because if they are inelastic, then they will still purchase or sell the good even as prices change. The more elastic group is willing to stop buying or selling the product and so their price will be less effected. Move the demand curve on the graph below to see how the prices change as their demand is more and less elastic for the $2.52 soda tax above.


## Subsidies

Subsidies are the opposite of a tax. Instead of giving the government money, the government gives money to either consumers for purchasing a product, or to producers for making and selling a product. IF a subsidy is given to consumers, then they will receive additional benefit (increase their demand) for the product. This increases the market equilibrium quantity. Consumers will still pay producers a high price for the good or service, but after purchase they will get some of their money back through the subside, ultimately making the final price lower for consumers. If the market was efficient before the subsidy, then the additional production leads to deadweight loss.

Similar to taxes, we can also subsidize the firms producing a good or service. Just like with taxes, the final market prices and quantities will be the same regardless of who the subsidy is given too. We will do a deeper dive into subsidies once we get to the chapter on externalities.

